version: "3"

services:
   app:
     build: .
     command: npm start
     ports:
        - "3033:3033"
     volumes:
        - .:/user/app
     networks:
      - minha-rede

   my-mysql:
    image: mysql:5.7.24
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - minha-rede

networks:
  minha-rede: